### ISSUE TITLE
.NARG counts definition not call

### ISSUE THREAD

**Issue by slcasner** [shattered/macro11#4]
It looks like the .NARGs pseudo-op returns the number of arguments in the macro definition, not the number of arguments supplied when the macro is called.  If that is correct, it's a bug.

**Comment by Rhialto** [comment]
I have a fork of this macro11, and I have a test case for this: https://github.com/Rhialto/macro11/blob/master/tests/test-macro-comma.lst.ok is the output and (at least with the fork) seems to do the right thing, doesn't it?
It looks like I fixed .NARG in commit 4fabe28497d925bd9d6d34886a48bbb07b4a9955.
(Interestingly, clicking on that commit id makes it seem I committed something to shattered's repo. I didn't; it is in my fork)

**Comment by slcasner** [comment]
I think the problem is that when a macro was called there would be default empty arguments supplied for those that were not present in the source file.  A solution is to change new_macro_stream() to not count args with empty labels.

**Comment by slcasner** [comment]
Sorry Rhialto, I didn't see your comment before mine because I was off doing some debugging myself for this issue and another that I will post shortly.  I think your fix is better than what I did.

**Comment by slcasner** [comment]
My other issue was the truncation of local symbols that you fixed in a6ee20c.  I should have looked for your fork to start with.  I have two questions though (and sorry this is not the proper place):
1. You made a change to allow quotes on .INCLUDE filenames, but I find that your fork _requires_ quotes, which my files don't have.  Is that what you intended?
2. I need the RT11 object format.  Where did you intend the RT11 conditional to be defined?

**Comment by Rhialto** [comment]
1. Yes, that is intentional. The manual, in 6.10.2, speaks of a delimited string and gives some examples (is a bit vague on what delimiters are actually allowed though).
   "The Manual" I'm refering to is AA-KX10A-TC_PDP-11_MACRO-11_Reference_Manual_May88.pdf at http://www.bitsavers.org/pdf/dec/pdp11/rsx11/RSX11Mplus_V4.x/4a/
2. I don't think I actually tried doing that, since I didn't have a reference to test against. Try adding -DRT11 in the Makefile and using mlb.c instead of mlb-rsx.c. Hopefully none of the other things I changed moved away from the result you're after.
